/**:
  ros__parameters:
    gap_angle_topic: "/autonomous/ftg/gap_angle"
    target_speed_topic: "/autonomous/ftg/target_speed"
    ackermann_cmd_topic: "/autonomous/ackermann_cmd"
    control_status_topic: "/autonomous/ftg/control_status"
    frame_id: "base_link"
    
    input_timeout_sec: 0.50
    publish_zero_on_stale: true
    
    angle_to_steering_gain: -1.00   # invertiert, Hardware-spezifisch
    max_steering_angle_rad: 0.45
    
    min_speed_mps: 0.0
    max_speed_mps: 1.80
